### ISSUE TITLE
Coding standards improvements

### ISSUE THREAD

**Issue by tarasterletskij** [bitbag-commerce/dhl-shipping-export-plugin#4]
Hi, guys I think, I found problem with namespace. In SyliusShippingExportPlugin on version 1.2 was changing namespace from BitBagShippingExportPlugin to BitBagSyliusShippingExportPlugin. Right now I can't install SyliusDHL24PlShippingExportPlugin because there are problem with "minimum-stability". But when install two plugins with @dev all installed :),  but there is Exception: 

> PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to BitBag\Dhl24PlShippingExportPlugin\EventListener\ShippingExportEventListener::exportShipment() must be an instance of BitBag\ShippingExportPlugin\Event\ExportShipmentEvent, instance of BitBag\SyliusShippingExportPlugin\Event\ExportShipmentEvent given

**Comment by damonsson** [comment]
Fixed by #7
